# Generated by Django 2.2 on 2019-04-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300)),
                ('query', models.CharField(max_length=120)),
                ('deep', models.IntegerField(default=0)),
            ],
        ),
    ]
